export type GuardrailLevel = "Low" | "Medium" | "High" | "Severe";
export type RiskBand = "Low" | "Medium" | "High" | "Very High";
export type Reliability = "high" | "medium" | "low" | "not_suitable" | "assumption_based";

export interface FairnessV2Action {
  lsoa21cd?: string;
  lsoa21nm?: string | null;
  borough?: string;
  month?: string;
  fairness_reduction_priority?: string;
  dominant_unfairness_pattern?: string;
  v2_score_explanation?: string;
  actionable_fairness_score_0_100?: number;
  estimated_post_reduction_fairness_score_0_100?: number;
  estimated_fairness_gain_score_points?: number;
  estimated_trust_legitimacy_gain_0_100?: number;
  expected_monthly_search_volume?: number;
  relevant_crime_target?: string;
  baseline_predicted_relevant_crime?: number;
  estimated_post_reduction_relevant_crime?: number;
  response_estimation_method?: string;
  response_model_reliability?: Reliability;
  intervention_unit_id?: string;
  intervention_unit_type?: string;
  borough_or_bcu?: string;
  quarter?: string;
  pathway_type?: string;
  category?: string;
  reduction_category: string;
  eligible_lsoa_count?: number;
  high_priority_lsoa_count?: number;
  expected_eligible_search_volume?: number;
  proposed_reduction_pct?: number;
  expected_searches_reduced: number;
  expected_no_result_stops_avoided: number;
  expected_positive_outcomes_forgone: number;
  expected_arrests_forgone: number;
  crime_guardrail_summary?: GuardrailLevel;
  trust_context_warning?: boolean;
  actionability_status?: string;
  recommendation_explanation?: string;
  scenario_id?: string;
  estimated_relevant_crime_change_lower_bound?: number;
  estimated_relevant_crime_change_upper_bound?: number;
  response_interpretation_warning?: string;
  lsoa_unit_membership_explanation?: string;
}

export interface LsoaDetail extends MapFeatureProps {
  racial_disproportionality_score_0_100: number | null;
  deprivation_exposure_score_0_100: number | null;
  excess_stop_share: number | null;
  data_reliability: string;
  trust_context_band: string | null;
  trust_context_score_0_100: number | null;
  racial_monitor_groups?: string | null;
  very_low_yield_categories?: string | null;
  racial_oversearch_low_yield_groups?: string | null;
  max_reduction_cap_from_crime_guardrail: number;
  crime_guardrail_explanation: string;
  eligible_for_numeric_reduction: boolean;
  scenario_id: string;
  primary_v2_action?: FairnessV2Action | null;
  v2_actions?: FairnessV2Action[];
  action: Record<string, unknown> | null;
  recommendation_explanation: string;
  trust_warning?: string;
}

export type MapFeatureProps = {
  lsoa21cd: string;
  lsoa21nm: string;
  borough: string;
  low_yield_score_0_100: number | null;
  over_search_score_0_100: number | null;
  stop_burden_score_0_100: number | null;
  crime_guardrail_level: GuardrailLevel;
  borough_low_trust_flag: boolean;
  overall_review_priority?: string | null;
  criticalness_score?: number | null;
  criticalness_level?: string | null;
  actionable_fairness_score_0_100?: number | null;
  fairness_reduction_priority?: string | null;
  v2_reduction_candidate_flag?: boolean | null;
  dominant_unfairness_pattern?: string | null;
  fairness_pathway_labels?: string | null;
  substantial_oversearch_flag?: boolean | null;
  much_oversearch_flag?: boolean | null;
  deprivation_trait_flag?: boolean | null;
  oversearch_trait_flag?: boolean | null;
  much_oversearch_trait_flag?: boolean | null;
  low_yield_trait_flag?: boolean | null;
  racial_trait_flag?: boolean | null;
  very_low_yield_trait_flag?: boolean | null;
  monitor_trait_count?: number | null;
  monitor_trait_labels?: string | null;
  independent_flag_count?: number | null;
  any_independent_flag?: boolean | null;
  deprivation_oversearch_path_flag?: boolean | null;
  deprivation_oversearch_low_yield_flag?: boolean | null;
  racial_oversearch_low_yield_flag?: boolean | null;
  racial_oversearch_low_yield_path_flag?: boolean | null;
  extreme_oversearch_low_yield_flag?: boolean | null;
  oversearch_low_yield_path_flag?: boolean | null;
  intervention_actionability_status?: string | null;
  excess_burden_score_0_100?: number | null;
  excess_burden_flag?: boolean | null;
  excess_burden_reason?: string | null;
  deprivation_burden_score_0_100?: number | null;
  deprivation_burden_flag?: boolean | null;
  deprivation_burden_reason?: string | null;
  racial_pathway_black_score_0_100?: number | null;
  racial_pathway_black_flag?: boolean | null;
  racial_pathway_black_reason?: string | null;
  racial_pathway_asian_score_0_100?: number | null;
  racial_pathway_asian_flag?: boolean | null;
  racial_pathway_asian_reason?: string | null;
  racial_pathway_mixed_score_0_100?: number | null;
  racial_pathway_mixed_flag?: boolean | null;
  racial_pathway_mixed_reason?: string | null;
  racial_pathway_other_score_0_100?: number | null;
  racial_pathway_other_flag?: boolean | null;
  racial_pathway_other_reason?: string | null;
  racial_pathway_white_score_0_100?: number | null;
  racial_pathway_white_flag?: boolean | null;
  racial_pathway_white_reason?: string | null;
  low_yield_actionability_score_0_100?: number | null;
  low_yield_actionability_flag?: boolean | null;
  low_yield_actionability_reason?: string | null;
  very_low_yield_actionability_flag?: boolean | null;
  trust_context_warning_flag?: boolean | null;
  trust_context_warning_text?: string | null;
  resident_denominator_caution_flag?: boolean | null;
  eligible_reduction_categories?: string | null;
  very_low_yield_categories?: string | null;
  stop_rate_per_1000?: number | null;
  london_avg_lsoa_stop_rate_per_1000?: number | null;
  london_normal_lsoa_stop_rate_per_1000?: number | null;
  stop_rate_vs_london_lsoa_avg_ratio?: number | null;
  excess_searches_to_london_lsoa_normal_annual?: number | null;
  excess_searches_to_london_lsoa_normal_month?: number | null;
  risk_band_total_crime_count?: RiskBand;
  risk_band_violence_count?: RiskBand;
  risk_band_drugs_count?: RiskBand;
  risk_band_robbery_count?: RiskBand;
  risk_band_possession_of_weapons_count?: RiskBand;
  trust_context_warning?: boolean;
  v2_action_count?: number;
  v2_proposed_reduction_pct?: number;
  v2_reduction_category?: string | null;
  v2_expected_searches_reduced?: number | null;
  v2_expected_no_result_stops_avoided?: number | null;
  proposed_reduction_pct: number;
  reduction_category: string | null;
  review_only?: boolean;
  expected_no_result_stops_avoided?: number;
  expected_arrests_forgone?: number;
  estimated_crime_change_lower_bound?: number;
  estimated_crime_change_upper_bound?: number;
};

export type FeatureCollection = {
  type: "FeatureCollection";
  features: { type: "Feature"; properties: MapFeatureProps; geometry: unknown }[];
};

export interface WardClusterProps {
  cluster_id: string;
  cluster_name: string;
  member_ward_names: string;
  boroughs: string;
  dominant_fairness_pathway: string;
  primary_search_regime?: string;
  quarterly_baseline_reducible_searches?: number;
  proposed_reduction_pct?: number;
  expected_quarterly_searches_reduced?: number;
  expected_quarterly_no_result_stops_avoided?: number;
  expected_quarterly_positive_outcomes_forgone?: number;
  expected_quarterly_arrests_forgone?: number;
  expected_quarterly_unfair_searches_to_london_normal?: number;
  expected_quarterly_excess_searches_to_london_avg?: number;
  excess_searches_to_london_normal_annual?: number;
  london_avg_ward_stop_rate_per_1000?: number;
  london_normal_ward_stop_rate_per_1000?: number;
  ward_stop_rate_vs_london_avg_ratio?: number;
  search_review_unfair_searches_qtr?: number;
  search_review_london_average_excess_qtr?: number;
  aggregate_crime_guardrail?: GuardrailLevel;
  estimated_crime_response_lower_bound?: number;
  estimated_crime_response_upper_bound?: number;
  trust_context_warning?: boolean;
  resident_denominator_caution?: boolean;
  recommendation_explanation?: string;
  allocated_package_id?: string;
  allocated_package_name?: string;
  protection_need_band?: string;
  quarterly_total_encounters?: number;
  search_review_total_qtr?: number;
  search_review_no_result_qtr?: number;
  search_review_no_result_rate?: number;
  search_review_positive_qtr?: number;
  search_review_low_result_signal?: number;
  search_review_main_type?: string;
  search_review_recommended_pct?: number;
  search_review_target_type?: string;
  search_review_action?: string;
  search_review_recommendation_state?: string;
  search_review_expected_searches_reduced?: number;
  search_review_expected_no_result_avoided?: number;
  search_review_expected_positives_at_risk?: number;
  predicted_serious_harm_per_1000_residents?: number;
  london_serious_harm_avg_per_1000_residents?: number;
  predicted_serious_harm_rank_pct?: number;
  predicted_harm_weighted_serious_crime_score_per_1000_residents?: number;
  london_harm_weighted_serious_crime_score_avg_per_1000_residents?: number;
  predicted_harm_weighted_serious_crime_score_rank_pct?: number;
  [key: string]: unknown;
}

export interface WardClusterFeatureCollection {
  type: "FeatureCollection";
  features: { type: "Feature"; properties: WardClusterProps; geometry: unknown }[];
}
