from __future__ import annotations

from src import config as base


ALPHA = base.FAIRNESS_V2_EMPIRICAL_BAYES_ALPHA
LATEST_MONTH = base.OUTPUT_LATEST_MONTH
INTERVENTION_PERIOD = base.INTERVENTION_PERIOD

MIN_LSOA_DISPLAY_STOPS_12M = base.FAIRNESS_V2_MIN_LSOA_DISPLAY_STOPS_12M
MIN_LSOA_STRONG_STOPS_12M = base.FAIRNESS_V2_MIN_LSOA_STRONG_STOPS_12M
MIN_CATEGORY_STOPS_12M = base.FAIRNESS_V2_MIN_CATEGORY_STOPS_12M
MIN_KNOWN_ETHNICITY_STOPS_12M = base.FAIRNESS_V2_MIN_KNOWN_ETHNICITY_STOPS_12M
MIN_GROUP_STOPS_12M = base.FAIRNESS_V2_MIN_GROUP_STOPS_12M
MIN_GROUP_POP_SHARE = base.FAIRNESS_V2_MIN_GROUP_POP_SHARE

LOW_YIELD_PROB_THRESHOLD = base.FAIRNESS_V2_LOW_YIELD_PROB_THRESHOLD
STRONG_LOW_YIELD_PROB_THRESHOLD = base.FAIRNESS_V2_STRONG_LOW_YIELD_PROB_THRESHOLD
OVERSEARCH_NORMAL_TOLERANCE = 1.25
SUBSTANTIAL_OVERSEARCH_RATIO = 1.25
MUCH_OVERSEARCH_RATIO = 1.50
LOW_YIELD_MARGIN = 0.05
VERY_LOW_YIELD_MARGIN = 0.10

REDUCIBLE_CATEGORIES = list(base.FAIRNESS_V2_REDUCIBLE_CATEGORIES)
PROTECTED_CATEGORIES = list(base.FAIRNESS_V2_PROTECTED_CATEGORIES)
ATOMIC_REDUCIBLE_CATEGORIES = ["drugs", "stolen_property", "other_non_weapon"]
ALL_CATEGORY_BUCKETS = ATOMIC_REDUCIBLE_CATEGORIES + ["offensive_weapons", "unknown_object"]

RACIAL_GROUPS = ["black", "asian", "mixed", "other", "white"]
RACIAL_GROUP_LABELS = {
    "black": "Black",
    "asian": "Asian",
    "mixed": "Mixed",
    "other": "Other",
    "white": "White",
}

CENTRAL_BOROUGH_DENOMINATOR_CAUTION = set(base.FAIRNESS_V2_CENTRAL_BOROUGH_DENOMINATOR_CAUTION)
